"""channel_listings에 match_status/match_score 추가

Revision ID: 3ecafe160c3a
Revises: b248bf902293
Create Date: 2026-04-24 14:48:27.529722
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "3ecafe160c3a"
down_revision: str | None = "b248bf902293"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # 기존 행은 모두 'CONFIRMED'로 채움 (지금까지의 매칭은 SKU 일치/사용자 의도 등록).
    # server_default를 임시로 두어 backfill 후 제거.
    op.add_column(
        "channel_listings",
        sa.Column("match_status", sa.String(length=20), nullable=False, server_default="CONFIRMED"),
    )
    op.alter_column("channel_listings", "match_status", server_default=None)
    op.add_column("channel_listings", sa.Column("match_score", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_channel_listings_match_status"), "channel_listings", ["match_status"], unique=False)
    op.create_index(op.f("ix_orders_channel_type"), "orders", ["channel_type"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_channel_type"), table_name="orders")
    op.drop_index(op.f("ix_channel_listings_match_status"), table_name="channel_listings")
    op.drop_column("channel_listings", "match_score")
    op.drop_column("channel_listings", "match_status")
    # ### end Alembic commands ###
