"""product_price_history 테이블 추가

Revision ID: 7bc151c55add
Revises: 3ecafe160c3a
Create Date: 2026-04-24 15:23:24.625384
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "7bc151c55add"
down_revision: str | None = "3ecafe160c3a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_price_history",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("field", sa.String(length=20), nullable=False),
        sa.Column("old_value", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("new_value", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("change_mode", sa.String(length=20), nullable=True),
        sa.Column("change_value", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("channel_results", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reverted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reverted_by_history_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["reverted_by_history_id"],
            ["product_price_history.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_product_price_history_batch_id"), "product_price_history", ["batch_id"], unique=False)
    op.create_index(op.f("ix_product_price_history_product_id"), "product_price_history", ["product_id"], unique=False)
    op.create_index(op.f("ix_product_price_history_user_id"), "product_price_history", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_product_price_history_user_id"), table_name="product_price_history")
    op.drop_index(op.f("ix_product_price_history_product_id"), table_name="product_price_history")
    op.drop_index(op.f("ix_product_price_history_batch_id"), table_name="product_price_history")
    op.drop_table("product_price_history")
    # ### end Alembic commands ###
